# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.IntegerField(null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_left', models.DateField(auto_now=True)),
                ('date_paid', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'db_table': 'Camera',
            },
        ),
    ]
