# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='date_left',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='date_paid',
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
