# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradetail',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad')], max_length=200),
        ),
    ]
