# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0002_auto_20180630_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('Lights', 'Lights'), ('Screens', 'Screens'), ('Sound', 'Sound')], max_length=200)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
