# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0003_auto_20180315_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradetail',
            name='status',
            field=models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('B', 'Bad')], max_length=20),
        ),
    ]
