# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20, null=True)),
                ('p_serial_number', models.CharField(max_length=20, null=True)),
                ('date_added', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad')], max_length=200)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psmsapp.CameraTypes')),
            ],
        ),
    ]
