# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0004_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
