# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0004_auto_20180316_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psmsapp.CameraDetail')),
            ],
            options={
                'db_table': 'CameraType',
                'verbose_name_plural': 'CameraTypes',
                'verbose_name': 'CameraType',
            },
        ),
    ]
