# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0005_auto_20180701_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('book', 'book'), ('assigned', 'assigned'), ('free', 'free')], max_length=200)),
            ],
            options={
                'verbose_name': 'AssignTools',
                'verbose_name_plural': 'AssignTools',
                'db_table': 'AssignTools',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='Equipment',
        ),
        migrations.AddField(
            model_name='assigntools',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psmsapp.Employee'),
        ),
        migrations.AddField(
            model_name='assigntools',
            name='equipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psmsapp.Equipment'),
        ),
    ]
