# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0005_cameratypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('B', 'Bad')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cameratypes',
            name='camera_type',
        ),
        migrations.AddField(
            model_name='cameradetail',
            name='camera_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psmsapp.CameraTypes'),
        ),
        migrations.AddField(
            model_name='cameratypes',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cameradetail',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cameradetail',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psmsapp.StatusChoices'),
        ),
    ]
