# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0007_auto_20180316_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusChoices',
        ),
    ]
