# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0007_auto_20180701_1108'),
        ('psmsapp', '0002_auto_20180427_0431'),
    ]

    operations = [
    ]
