# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0008_merge_20180703_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='label',
        ),
    ]
