# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0008_delete_statuschoices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cameratypes',
            table='CameraTypes',
        ),
    ]
