# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0009_auto_20180703_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
