# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0012_auto_20180703_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntools',
            name='availability',
        ),
        migrations.AddField(
            model_name='equipment',
            name='availability',
            field=models.CharField(choices=[('book', 'book'), ('assign', 'assign'), ('free', 'free')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
