# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0013_auto_20180703_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='availability',
            field=models.CharField(choices=[(b'book', b'book'), (b'assign', b'assign'), (b'free', b'free')], default=b'free', max_length=200),
        ),
    ]
