# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0014_auto_20180703_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='availability',
            field=models.CharField(choices=[('book', 'book'), ('assign', 'assign'), ('free', 'free')], default='free', max_length=200),
        ),
    ]
