# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0015_auto_20180703_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntools',
            name='condition_onreturn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assigntools',
            name='condition_ontake',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assigntools',
            name='date_returned',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assigntools',
            name='date_taken',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
