# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psmsapp', '0016_auto_20180703_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='_type',
            new_name='equipment_type',
        ),
    ]
